# Swag Reverse Proxy Config file
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name staging.giaidau.hcmusec.com;

    include /config/nginx/ssl.conf;

    client_max_body_size 20M;

    location ^~ /api/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app api;
        set $upstream_port 8000;
        set $upstream_proto http;

        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location ^~ /admin/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app api;
        set $upstream_port 8000;
        set $upstream_proto http;

        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location ^~ /static/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app api;
        set $upstream_port 8000;
        set $upstream_proto http;

        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location ^~ /media/payment-proofs/ {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app api;
        set $upstream_port 8000;
        set $upstream_proto http;

        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app web;
        set $upstream_port 3000;
        set $upstream_proto http;

        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}