# Generated by Django 6.0.7 on 2026-09-12 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_institution_enrichment"),
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="contact_discord_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="registration",
            name="contact_email_snapshot",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="registration",
            name="contact_facebook_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="registration",
            name="contact_phone_snapshot",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="registration",
            name="manager_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="registration",
            name="submitter_role",
            field=models.CharField(
                blank=True,
                choices=[("captain", "Captain"), ("manager", "Manager")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="registrationmember",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_members",
                to="accounts.institution",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registrationmember",
            name="school_snapshot",
            field=models.CharField(max_length=255),
        ),
    ]
