# Generated by Django 6.0.7 on 2026-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0003_member_roster_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationmember",
            name="date_of_birth_snapshot",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AddField(
            model_name="registrationmember",
            name="first_name_snapshot",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="registrationmember",
            name="last_name_snapshot",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="registrationmember",
            name="student_id_snapshot",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="student ID"
            ),
        ),
    ]
