# Generated by Django 6.0.7 on 2026-09-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0004_registrationmember_date_of_birth_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="team_tag",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
