# Generated by Django 6.0.7 on 2026-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0006_paymentintent"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="transfer_content",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="transfer_content_limit",
            field=models.PositiveSmallIntegerField(default=100, editable=False),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="transfer_content_template",
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
    ]
