# Generated by Django 6.0.7 on 2026-09-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0007_paymentintent_transfer_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentintent",
            name="transfer_content_template",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
