# Generated by Django 6.0.7 on 2026-09-14 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0008_alter_paymentintent_transfer_content_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="account_holder_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="account_number_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=19),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="bank_bin_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="bank_name_snapshot",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="registration",
            name="payment_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="payment_hold_minutes_snapshot",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(1440),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="registrationstatusevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                ("bank_bin", models.CharField(blank=True, default="", max_length=6)),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=19),
                ),
                (
                    "account_holder",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "payment_hold_minutes",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "payment settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="payment_settings_singleton_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payment_hold_minutes__range", (15, 1440))),
                        name="payment_settings_hold_minutes_range",
                    ),
                ],
            },
        ),
    ]
