# Generated by Django 6.0.7 on 2026-09-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0009_payment_settings_and_reservations"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("request_digest", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_access",
                        to="registrations.registration",
                    ),
                ),
            ],
        ),
    ]
