# Generated by Django 6.0.7 on 2026-09-16 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0010_registration_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bin",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[0-9]{6}\\Z", "Enter exactly six ASCII digits."
                            )
                        ],
                        verbose_name="BIN",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                ("swift_code", models.CharField(blank=True, max_length=50)),
                (
                    "transfer_supported",
                    models.BooleanField(
                        default=False,
                        help_text="The provider reports that this bank's app can scan VietQR.",
                    ),
                ),
                ("lookup_supported", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("short_name", "bin"),
            },
        ),
    ]
