# Generated by Django 6.0.7 on 2026-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0011_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationmember",
            name="school_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
