# Generated by Django 6.0.7 on 2026-07-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('starts_at__lt', models.F('ends_at')), _connector='OR'), name='tournament_starts_before_ends')],
            },
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size_min', models.PositiveSmallIntegerField()),
                ('team_size_max', models.PositiveSmallIntegerField()),
                ('registration_opens_at', models.DateTimeField()),
                ('registration_closes_at', models.DateTimeField()),
                ('registration_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_currency', models.CharField(default='VND', max_length=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_games', to='tournaments.game')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_games', to='tournaments.tournament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tournament', 'game'), name='unique_tournament_game'), models.CheckConstraint(condition=models.Q(('team_size_min__gte', 1)), name='tournament_game_min_team_size_positive'), models.CheckConstraint(condition=models.Q(('team_size_max__gte', models.F('team_size_min'))), name='tournament_game_max_team_size_at_least_min'), models.CheckConstraint(condition=models.Q(('registration_opens_at__lt', models.F('registration_closes_at'))), name='tournament_game_registration_window_valid'), models.CheckConstraint(condition=models.Q(('registration_capacity__isnull', True), ('registration_capacity__gt', 0), _connector='OR'), name='tournament_game_capacity_positive_or_null'), models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='tournament_game_fee_non_negative')],
            },
        ),
    ]
