# Generated by Django 6.0.7 on 2026-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/covers/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
