# Generated by Django 6.0.7 on 2026-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_main_roster_and_substitutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="students_only",
            field=models.BooleanField(
                default=False,
                help_text="Require a student ID for every player. Organizers review student eligibility.",
            ),
        ),
    ]
