# Generated by Django 6.0.7 on 2026-09-14 15:49

import django.core.validators
import tournaments.payment_content
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_tournament_students_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="transfer_content_limit",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Maximum characters accepted by the receiving bank (default 100, up to 150). Content is never truncated.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="transfer_content_template",
            field=models.CharField(
                default="{participant} thanh toan le phi {tournament_name}",
                help_text="Bank transfer text. Use {participant} for the team tag or solo in-game name, and {tournament_name} for the event name. Accents are removed automatically.",
                max_length=300,
                validators=[tournaments.payment_content.validate_transfer_template],
            ),
        ),
    ]
