# Generated by Django 6.0.7 on 2026-07-29

from django.db import migrations, models
import django.db.models.deletion


def migrate_school_to_institution(apps, schema_editor):
    Institution = apps.get_model("accounts", "Institution")
    User = apps.get_model("accounts", "User")

    for user in User.objects.exclude(school="").order_by("pk"):
        label = " ".join(user.school.split())
        if not label:
            continue
        normalized_label = label.casefold()
        institution = Institution.objects.filter(
            source="CUSTOM", normalized_label=normalized_label
        ).first()
        if institution is None:
            institution = Institution.objects.create(
                label=label,
                normalized_label=normalized_label,
                source="CUSTOM",
                review_status="PENDING",
            )
        user.institution = institution
        user.save(update_fields=("institution",))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_gamer_tag_add_student_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=32)),
                ("label", models.CharField(max_length=255)),
                ("normalized_label", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(blank=True, max_length=64)),
                ("short_name", models.CharField(blank=True, max_length=255)),
                ("english_name", models.CharField(blank=True, max_length=255)),
                ("type", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("CATALOGUE", "Catalogue"), ("CUSTOM", "Custom")],
                        default="CUSTOM",
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source", "CATALOGUE")),
                        fields=("source", "value"),
                        name="unique_catalogue_institution_value",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("source", "CUSTOM")),
                        fields=("source", "normalized_label"),
                        name="unique_custom_institution_label",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.institution",
            ),
        ),
        migrations.RunPython(migrate_school_to_institution, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="school",
        ),
    ]
