# Generated by Django 6.0.7 on 2026-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_institution_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="institution",
            name="domains",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="institution",
            name="provenance",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
